services:
  app:
    build: .
    container_name: Stock_Market_Price_Prediction_Project
    volumes:
      - .:/app
    command: python -m src.main

  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
#-----------------------------------------------
# in the root folder, open terminal and run this:
# docker compose up --build app
